#!/bin/ksh
# vim: set ts=4 sw=4 et:

#PATH=/usr/bin:/usr/sbin
#PATH=/opt/altsys/bin:/opt/altsys/usr/bin:/opt/altsys/usr/sbin:/opt/altsys/sbin:/opt/AltSys/core/usr/bin:/opt/AltSys/toybox/bin:/opt/AltSys/toybox/sbin:/opt/AltSys/toybox/usr/bin:/opt/AltSys/toybox/usr/sbin:/opt/AltSys/misc/bin:/opt/AltSys/obase/ubase/bin:/opt/AltSys/obase/sbase/bin:/usr/bin:/usr/sbin
RECUR_TO_UUTILS=1 . /etc/profile
export PATH

. /etc/runit/functions

msg "Welcome to Void!"

[ -r /etc/rc.conf ] && . /etc/rc.conf

# Start core services: one-time system tasks.
detect_virt
for f in /etc/runit/core-services/*.sh; do
	[ -r $f ] && . $f
done

dmesg >/var/log/dmesg.log
if [ $(sysctl -n kernel.dmesg_restrict 2>/dev/null) -eq 1 ]; then
	chmod 0600 /var/log/dmesg.log
else
	chmod 0644 /var/log/dmesg.log
fi

# create files for controlling runit
mkdir -p /run/runit
install -m 000 /dev/null /run/runit/stopit
install -m 000 /dev/null /run/runit/reboot

msg "Initialization complete, running stage 2..."
