#!/bin/ksh
# vim: set ts=4 sw=4 et:

#PATH=/usr/bin:/usr/sbin
PATH=/opt/AltSys/core/usr/bin:/opt/AltSys/toybox/bin:/opt/AltSys/toybox/sbin:/opt/AltSys/toybox/usr/bin:/opt/AltSys/toybox/usr/sbin:/opt/AltSys/misc/bin:/opt/AltSys/obase/sbase:/opt/AltSys/obase/ubase:/usr/bin:/usr/sbin

. /etc/runit/functions
detect_virt
[ -r /etc/rc.conf ] && . /etc/rc.conf
echo
for f in /etc/runit/shutdown.d/*.sh; do
	[ -r $f ] && . $f
done
